samba:
  image: rsippl/samba-ad-dc
  # Ports not needed because we link the containers
  ports:
    - 53:53
    - 53:53/udp
  #   - 88:88
  #   - 88:88/udp
  #   - 135:135
  #   - 137-138:137-138/udp
  #   - 139:139
    - 389:389
    - 389:389/udp
  #   - 445:445
  #   - 464:464
  #   - 464:464/udp
  #   - 636:636
  #   - 1024-1044:1024-1044
  #   - 3268-3269:3268-3269
  container_name: samba
  hostname: ad
  domainname: dtux.org
  environment:
    - SAMBA_DOMAIN=DTUX
    - SAMBA_REALM=DTUX.ORG
    - ROOT_PASSWORD=D13g@anna
    - SAMBA_ADMIN_PASSWORD=T0p$$ecret
    - LDAP_ALLOW_INSECURE=true
  dns: 127.0.0.1
  dns_search: dtux.org
  privileged: true

dhcpd:
  image: diegograssato/dhcpd
  net: host
  volumes:
    # Config pass through
    - ./dhcpd/dhcpd.conf:/etc/dhcp/dhcpd.conf
  privileged: true
